// src/app/layout.js (现在是服务器组件，没有 "use client")
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// 导入新的客户端包装组件

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// metadata 可以在这里导出，因为 layout.js 现在是服务器组件
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // 移除 userStore 相关的状态和 useEffect 逻辑
  // const { initAuth, token, user } = userStore(); // 移除
  // useEffect(() => { ... }, [initAuth, token]); // 移除

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          {children}
      </body>
    </html>
  );
}